_SpecStatsCollect: fix bug in '_separate_inb_vs_oob()'
Previously, '_separate_inb_vs_oob()' relied on the initialisation of
'self._inbagent' and 'self._oobagent'. The latter is not always
initialised. Therefore this patch reworks '_separate_inb_vs_oob()' to
only split out-of-band statistics if they are available (if
'self._oobagent' is initialised).

Fixes the following error:

Traceback (most recent call last):
  File "StatsCollect.py", line 539, in _separate_aggr_vs_specific
    spec_stnames = stnames & (set(self._inbagent.stinfo) | set(self._oobagent.stinfo))
AttributeError: 'NoneType' object has no attribute 'stinfo'

Signed-off-by: Adam Hawley <adam.james.hawley@intel.com>