stats-collect: do not crash when run from sources
When running 'stats-collect' from sources, it crashes like this:

raceback (most recent call last):
  File "/root/wult/helpers/stats-collect/stats-collect", line 32, in <module>
    from wultlibs.helperlibs import ProcHelpers
ModuleNotFoundError: No module named 'wultlibs'

This is because it resides in 'helpers/stats-collect' sub-directory, so it
can't find 'wultlibs'. Add the root project sources directory to the modules
search path to overcome the problem.

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>