Deploy: improve error message in Ubuntu
In Ubuntu, 'wult deploy --rebuild-bpf' fails with the following error:

/usr/bin/clang ... blah
make: Leaving directory '/tmp/wult-88uu6txs/wult-hrt-helper'
In file included from hrt-bpf.c:7:
In file included from /usr/src/linux-headers-5.15.0-43-generic/include/uapi/linux/bpf.h:11:
In file included from /usr/src/linux-headers-5.15.0-43-generic/include/linux/types.h:6:
/usr/src/linux-headers-5.15.0-43-generic/include/uapi/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
         ^~~~~~~~~~~~~
1 error generated.
make: *** [Makefile:44: hrt-bpf.o] Error 1

The 'asm/types.h' file is provided by the 'gcc-multilib' package, which is not
very obvious.

Add a user-friendly message suggesting to install the 'gcc-multilib' package.

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>