wultlibs/_common.py: fix -l validation
I accidentally ran wult as 'wult start -l <path>', while I meant to use
'-o <path>'. Wult crashed like this:

Traceback (most recent call last):
  File "...<cut>.../wult/wult", line 558, in <module>
    sys.exit(main())
  File "...<cut>.../wult/wult", line 548, in main
    args.func(args)
  File "...<cut>.../wult/wult", line 396, in start_command
    with WultRunner.WultRunner(proc, args.devid, res, args.ldist, args.force) as runner:
  File "...<cut>.../wult/wultlibs/WultRunner.py", line 326, in __init__
    self._ldist = _common.validate_ldist(self._ldist)
  File "...<cut>.../wult/wultlibs/_common.py", line 26, in validate_ldist
    if ldst[idx] <= 0:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'

This patch fixes the problem: before verifying the range, we need to verify
whether 'ldist' is an integer.

Change-Id: Ie1a0e418535972a030000b763b5350652c4891b7
Signed-off-by: Artem Bityutskiy <dedekind1@gmail.com>