Devices: fix crash with unknown device
One of recent patches introduced a regression, and this command crashes:

wult start hrt1

Traceback (most recent call last):
  ... snip ...
  File "wultlibs/Devices.py", line 296, in __init__
    if netif:
UnboundLocalError: local variable 'netif' referenced before assignment

This patch fixes the issue

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>