_DeployBPFHelpers: use list instead of set for include dirs parsing
Current usage of set in the incdirs variable results in random ordering
of the includes during compile. Quite often this causes compilation
errors of following sort:

In file included from hrt-bpf.c:15:
./common.h:42:2: error: unknown type name 'u8'
        u8 type;
        ^
./common.h:43:2: error: unknown type name 'u32'
        u32 ldist;

...

Fix the problem by converting the incdirs variable into a list, which
is inherently ordered.

Signed-off-by: Tero Kristo <tero.kristo@linux.intel.com>