ProcHelpers: fix crash in 'kill_pids()'
Caused by recent rework.

wultlibs/helperlibs/ProcHelpers.py", line 107, in kill_pids
AttributeError: 'NoneType' object has no attribute 'hostmsg'

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@intel.com>