setup.py: install stats-collect and ipmi-helper
Problem symptom:

$ wult deploy
Kernel sources path: /lib/modules/5.10.1/build
Kernel version: 5.10.1
Drivers will be compiled on host 'localhost'
Helpers will be compiled on host 'localhost'
Drivers will be deployed to '/lib/modules/5.10.1'
Kernel modules path: /lib/modules/5.10.1
Helpers will be deployed to '/root/.local/bin'
Compiling the drivers
Compiling the helpers
wult: error: the following command failed with exit code 2:
make -C '/tmp/wult-6sSN3k/helpers/stats-collect'
make: Entering directory '/tmp/wult-6sSN3k/helpers/stats-collect'
./prepare-standalone.sh
make: Leaving directory '/tmp/wult-6sSN3k/helpers/stats-collect'
Traceback (most recent call last):
  File "./stats-collect", line 30, in <module>
    from wultlibs.helperlibs import Logging, ArgParse, Procs, Trivial, ProcHelpers
ImportError: cannot import name 'Logging'
make: *** [Makefile:7: all] Error 1

Problem description

The controller system has multiple versions of python3. Wult was installed with
python 3.8, so all its modules are in '/lib/python3.8', or something like this.

The 'stats-collect' script shebang is '/usr/bin/python3', which is python 3.6.
When 'stats-collect' is executed, it cannot find the 'Logging' module, because
it was not installed for python 3.6.

Solution

Let setuptools install 'stats-collect' as a script, not as data. In this case
setuptools will adjust the shebang.

Additionally, adjust 'Makefile' to consistently use 'python3'. It was using both
'python' and 'python3' before this patch.

Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>