Deploy: fix typos in 'statscollectlibs' and 'wultlibs'
These typos caused the following error when running 'wult deploy':
  File "/root/applications.validation.server-powerlab.wult/wulttools/_Wult.py", line 318, in _deploy_command
    _WultDeploy.deploy_command(args)
  File "/root/applications.validation.server-powerlab.wult/wulttools/_WultDeploy.py", line 26, in deploy_command
    depl.deploy()
  File "/root/applications.validation.server-powerlab.wult/statscollectlibs/deploylibs/Deploy.py", line 221, in deploy
    self._adjust_installables()
  File "/root/applications.validation.server-powerlab.wult/wultlibs/deploylibs/Deploy.py", line 508, in _adjust_installables
    super()._adjust_installables()
  File "/root/applications.validation.server-powerlab.wult/statscollectlibs/deploylibs/Deploy.py", line 204, in _adjust_installables
    del self._insts[installable]
KeyError: 'stc-agent'

This regression was introduced in v1.10.45.

Signed-off-by: Adam Hawley <adam.james.hawley@intel.com>